### ISSUE TITLE
FileRollingAppender not naming files correctly

### ISSUE THREAD

**Issue by Joshuaweg** [fergie319/log4net.Csv#8] opened 2020-04-29 19:00 UTC
I am creating a set of csv log files using rolling file appender. I am getting the csv files fine. I am having issues when naming the other files statically. I was expecting <file_name.1.csv> but instead I am getting <file_name.csv.1> which is causing the computer to not recognize it as a csv file.

Here is my config:
 <log4net>
    <appender name="RollingFileAppender" type="log4net.Appender.RollingFileAppender">
      <file value="logs\MyLog.csv"/>
      <appendToFile value="true"/>
      <rollingStyle value="Size"/>
      <maxSizeRollBackups value="10"/>
      <maximumFileSize value="5MB"/>
      <staticLogFileName value="true"/>
      <layout type="log4net.Csv.CsvLayout, log4net.Csv">
        <header type="log4net.Util.PatternString" value="date,logger,thread,level,message,exception%newline" />
        <fields value="date,logger,thread,level,message,exception" />
      </layout>
    </appender>
    <root>
      <level value="ALL"/>
      <appender-ref ref="RollingFileAppender"/>
    </root>
  </log4net>
I cannot find anything online about a similar issue. Please Help

**Comment by fergie319** [comment] 2020-07-22 23:28
This is the default behavior of the RollingFileAppender.  I believe this was intentional, but I did not write the code.  This is an issue with the RollingFileAppender itself and is not applicable to this project.  In other words, there is no code in this project that has anything to do with the file names of log files.

If you believe this to be an issue, then you should open it against the log4net project.  However, I'm pretty sure they will close it because it is their intended behavior.  Also, while writing this I googled the project and found that Apache has marked it dormant: https://logging.apache.org/log4net/

If you're adventurous, you could have a look at the source code and see if you can track down the offending namer and create your own branch to fix it.

There is a github mirror here: https://github.com/apache/logging-log4net

Another approach would be to create your own appender derived from the RollingFileAppender and make your changes there in your own DLL.

**Closed as completed by fergie319** 2020-07-22 23:28 UTC
